use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::config::DnsConfig;
use crate::engine::evidence::VerificationResult;
use crate::engine::exec;
use crate::engine::module::{Context, Diagnosis, Module, Observation};
use crate::engine::plan::{Change, ChangePlan, Risk, ServiceActionKind};

const DNSMASQ_CONF_PATH: &str = "/etc/dnsmasq.d/01-debkit-local-zones.conf";
const TAILSCALE_RESOLV_BACKUP: &str = "/etc/resolv.pre-tailscale-backup.conf";

/// Only `dns.provider = "dnsmasq"` is declaratively managed — writing an authoritative
/// local zone + upstream forwarding into a DebKit-owned dnsmasq conf.d file, per the
/// doc's "declare the local zone explicitly" fix for local names being forwarded to
/// public resolvers and returning NXDOMAIN. `/etc/resolv.conf` itself is never written
/// here: it's normally dynamically regenerated by NetworkManager/systemd-resolved, so
/// rewriting it directly would just get silently overwritten on the next reconnect — a
/// real footgun. When the resolver path doesn't point at dnsmasq, that's surfaced as a
/// standing diagnostic finding instead (informational, matching identity.nis's
/// "uninitialized maps" precedent for a real gap this module doesn't auto-close).
///
/// Ownership conflicts (more than one resolver stack actively listening on port 53) are
/// detected from real listener state, not inferred intent — and `plan()` refuses to run
/// while one is active, per the doc's "never change a DNS/DHCP/firewall owner while a
/// competing owner is active" guardrail.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct DnsObservation {
    resolv_conf_current: Option<String>,
    resolv_conf_owner: Option<String>,
    search_domains: Vec<String>,
    port_53_listeners: Vec<String>,
    resolver_conflict: Option<Vec<String>>,
    dnsmasq_installed: bool,
    dnsmasq_active: bool,
    dnsmasq_conf_current: Option<String>,
    dnsmasq_conf_desired: Option<String>,
}

pub struct NetworkDns;

impl Module for NetworkDns {
    fn name(&self) -> &'static str {
        "network.dns"
    }

    fn discover(&self, ctx: &Context) -> anyhow::Result<Observation> {
        let config = &ctx.config.dns;

        let resolv_conf_current = fs::read_to_string("/etc/resolv.conf").ok();
        let resolv_conf_owner = detect_resolv_conf_owner(resolv_conf_current.as_deref());
        let search_domains = resolv_conf_current
            .as_deref()
            .map(parse_search_domains)
            .unwrap_or_default();

        let port_53_listeners = read_port_53_listeners();
        let resolver_conflict = detect_resolver_conflict(&port_53_listeners);

        let dnsmasq_installed = exec::command_available("dnsmasq");
        let dnsmasq_active = exec::systemctl_is_active("dnsmasq");
        let dnsmasq_conf_current = fs::read_to_string(DNSMASQ_CONF_PATH).ok();
        let dnsmasq_conf_desired = desired_dnsmasq_conf(config);

        let data = DnsObservation {
            resolv_conf_current,
            resolv_conf_owner,
            search_domains,
            port_53_listeners,
            resolver_conflict,
            dnsmasq_installed,
            dnsmasq_active,
            dnsmasq_conf_current,
            dnsmasq_conf_desired,
        };

        let mut observation = Observation::new(serde_json::to_value(&data)?);
        observation.owner = data.resolv_conf_owner.clone();
        if let Some(conflict) = &data.resolver_conflict {
            observation = observation.with_warning(format!(
                "more than one resolver appears to be actively listening on port 53: {}",
                conflict.join(", ")
            ));
        }
        if Path::new(TAILSCALE_RESOLV_BACKUP).exists() {
            observation = observation.with_warning(
                "resolv.conf is currently managed by tailscaled; local zone changes may not take effect until Tailscale's DNS behavior is reconciled (see network.tailscale)"
                    .to_string(),
            );
        }
        Ok(observation)
    }

    fn diagnose(&self, ctx: &Context, observation: &Observation) -> Diagnosis {
        if !ctx.config.dns.enabled {
            return Diagnosis::compliant();
        }

        let data: DnsObservation = match serde_json::from_value(observation.data.clone()) {
            Ok(data) => data,
            Err(err) => {
                return Diagnosis::mismatch(vec![format!(
                    "failed to read network.dns observation: {err}"
                )]);
            }
        };

        if let Some(conflict) = data.resolver_conflict {
            return Diagnosis::conflict(conflict);
        }

        let mut findings = Vec::new();
        if ctx.config.dns.provider == "dnsmasq" {
            if !data.dnsmasq_installed {
                findings.push("dnsmasq is not installed".to_string());
            }
            if data.dnsmasq_conf_current != data.dnsmasq_conf_desired {
                findings.push(format!(
                    "{DNSMASQ_CONF_PATH} does not match declared local zones/upstream"
                ));
            }
            if !data.dnsmasq_active {
                findings.push("dnsmasq is not active".to_string());
            }
            if data.resolv_conf_owner.as_deref() != Some("dnsmasq") {
                findings.push(format!(
                    "resolv.conf is owned by `{}`, not dnsmasq — local zone changes will not be used until the resolver path points at dnsmasq (not managed by this module; see the network manager's per-connection DNS override)",
                    data.resolv_conf_owner.as_deref().unwrap_or("unknown")
                ));
            }
        }

        if findings.is_empty() {
            Diagnosis::compliant()
        } else {
            Diagnosis::mismatch(findings)
        }
    }

    fn plan(
        &self,
        ctx: &Context,
        observation: &Observation,
        diagnosis: &Diagnosis,
    ) -> anyhow::Result<ChangePlan> {
        let mut plan = ChangePlan::new();
        if !ctx.config.dns.enabled || diagnosis.compliant {
            return Ok(plan);
        }
        if let Some(conflict) = &diagnosis.conflict {
            anyhow::bail!(
                "refusing to plan network.dns: competing resolvers are active on port 53 ({}); resolve the conflict before declaring a provider",
                conflict.join(", ")
            );
        }
        if ctx.config.dns.provider != "dnsmasq" {
            return Ok(plan);
        }

        let data: DnsObservation = serde_json::from_value(observation.data.clone())?;

        if !data.dnsmasq_installed {
            plan.push(
                "install dnsmasq",
                Risk::Medium,
                Change::InstallPackages {
                    packages: vec!["dnsmasq".to_string()],
                },
            );
        }

        let conf_changed = data.dnsmasq_conf_current != data.dnsmasq_conf_desired;
        if let Some(desired) = &data.dnsmasq_conf_desired
            && conf_changed
        {
            plan.push(
                format!("write {DNSMASQ_CONF_PATH} for declared local zones"),
                Risk::Medium,
                Change::WriteFile {
                    path: PathBuf::from(DNSMASQ_CONF_PATH),
                    content: desired.clone(),
                },
            );
        }

        if !data.dnsmasq_active {
            plan.push(
                "enable and start dnsmasq",
                Risk::Low,
                Change::ServiceAction {
                    unit: "dnsmasq".to_string(),
                    action: ServiceActionKind::EnableNow,
                },
            );
        } else if conf_changed {
            plan.push(
                "restart dnsmasq to apply local zone changes",
                Risk::Medium,
                Change::ServiceAction {
                    unit: "dnsmasq".to_string(),
                    action: ServiceActionKind::Restart,
                },
            );
        }

        Ok(plan)
    }

    fn verify(&self, ctx: &Context) -> anyhow::Result<Vec<VerificationResult>> {
        let config = &ctx.config.dns;
        if !config.enabled {
            return Ok(vec![VerificationResult::skipped(
                "network.dns",
                "disabled in config",
            )]);
        }

        let mut checks = Vec::new();
        let listeners = read_port_53_listeners();
        match detect_resolver_conflict(&listeners) {
            Some(conflict) => checks.push(VerificationResult::fail(
                "at most one resolver is listening on port 53",
                conflict.join(", "),
            )),
            None => checks.push(VerificationResult::pass(
                "at most one resolver is listening on port 53",
            )),
        }

        if config.provider == "dnsmasq" {
            for domain in &config.local_domains {
                let domain = domain.trim();
                if domain.is_empty() {
                    continue;
                }
                let check_name = format!("local zone `{domain}` resolves via dnsmasq");
                if !exec::command_available("dig") {
                    checks.push(VerificationResult::skipped(
                        check_name,
                        "`dig` is not installed",
                    ));
                    continue;
                }
                match exec::capture(
                    "dig",
                    &["@127.0.0.1", domain, "+short", "+time=2", "+tries=1"],
                ) {
                    Ok(raw) if !raw.trim().is_empty() => {
                        checks.push(VerificationResult::pass(check_name));
                    }
                    Ok(_) => checks.push(VerificationResult::fail(
                        check_name,
                        "dig returned no answer",
                    )),
                    Err(err) => checks.push(VerificationResult::fail(check_name, err.to_string())),
                }
            }
        }

        Ok(checks)
    }
}

fn detect_resolv_conf_owner(content: Option<&str>) -> Option<String> {
    if let Ok(target) = fs::read_link("/etc/resolv.conf") {
        let target = target.to_string_lossy();
        if target.contains("systemd/resolve") {
            return Some("systemd-resolved".to_string());
        }
        if target.contains("NetworkManager") {
            return Some("NetworkManager".to_string());
        }
    }
    if Path::new(TAILSCALE_RESOLV_BACKUP).exists() {
        return Some("tailscaled".to_string());
    }
    let content = content?;
    if content.contains("Generated by NetworkManager") {
        return Some("NetworkManager".to_string());
    }
    if content
        .lines()
        .any(|line| line.trim() == "nameserver 127.0.0.1")
        && exec::systemctl_is_active("dnsmasq")
    {
        return Some("dnsmasq".to_string());
    }
    Some("static".to_string())
}

fn parse_search_domains(content: &str) -> Vec<String> {
    content
        .lines()
        .find_map(|line| line.strip_prefix("search "))
        .map(|rest| rest.split_whitespace().map(str::to_string).collect())
        .unwrap_or_default()
}

fn read_port_53_listeners() -> Vec<String> {
    let Ok(raw) = exec::capture("ss", &["-tuln"]) else {
        return Vec::new();
    };
    raw.lines()
        .filter(|line| {
            line.split_whitespace()
                .nth(4)
                .is_some_and(|addr| addr.ends_with(":53"))
        })
        .map(str::trim)
        .map(str::to_string)
        .collect()
}

/// A `127.0.0.53:53` listener is systemd-resolved's stub convention; any *other*
/// loopback listener on port 53 at the same time means a second resolver stack
/// (dnsmasq, dnscrypt-proxy, etc.) is also actively serving — a real, observable
/// conflict rather than an inferred one.
fn detect_resolver_conflict(listeners: &[String]) -> Option<Vec<String>> {
    let has_resolved_stub = listeners.iter().any(|line| line.contains("127.0.0.53:53"));
    let has_other_loopback = listeners.iter().any(|line| {
        line.contains(":53") && !line.contains("127.0.0.53:53") && line.contains("127.0.0.1")
    });
    if has_resolved_stub && has_other_loopback {
        Some(vec![
            "systemd-resolved (127.0.0.53:53)".to_string(),
            "another resolver (127.0.0.1:53)".to_string(),
        ])
    } else {
        None
    }
}

fn desired_dnsmasq_conf(config: &DnsConfig) -> Option<String> {
    if config.provider != "dnsmasq" {
        return None;
    }
    let mut out = String::from("# Managed by DebKit.\n");
    if !config.listen.is_empty() {
        out.push_str(&format!("listen-address={}\n", config.listen.join(",")));
    }
    for domain in &config.local_domains {
        let domain = domain.trim();
        if domain.is_empty() {
            continue;
        }
        out.push_str(&format!("local=/{domain}/\n"));
        out.push_str(&format!("domain={domain}\n"));
    }
    let upstream = config.encrypted_upstream_address.trim();
    if !upstream.is_empty() {
        out.push_str(&format!("server={upstream}\n"));
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn module_name_matches_config_section() {
        assert_eq!(NetworkDns.name(), "network.dns");
    }

    #[test]
    fn parses_search_domains_line() {
        let content = "search dublinux.lan\nnameserver 10.0.0.1\n";
        assert_eq!(parse_search_domains(content), vec!["dublinux.lan"]);
    }

    #[test]
    fn desired_conf_renders_local_zone_and_upstream() {
        let config = DnsConfig {
            enabled: true,
            provider: "dnsmasq".to_string(),
            local_domains: vec!["dublinux.lan".to_string()],
            listen: vec!["127.0.0.1".to_string(), "10.0.0.1".to_string()],
            encrypted_upstream_address: "127.0.0.1:5053".to_string(),
        };
        let rendered = desired_dnsmasq_conf(&config).unwrap();
        assert!(rendered.contains("listen-address=127.0.0.1,10.0.0.1"));
        assert!(rendered.contains("local=/dublinux.lan/"));
        assert!(rendered.contains("domain=dublinux.lan"));
        assert!(rendered.contains("server=127.0.0.1:5053"));
    }

    #[test]
    fn desired_conf_is_none_for_other_providers() {
        let config = DnsConfig {
            enabled: true,
            provider: String::new(),
            ..Default::default()
        };
        assert_eq!(desired_dnsmasq_conf(&config), None);
    }

    #[test]
    fn conflict_detected_when_stub_and_other_loopback_both_listen() {
        let listeners = vec![
            "tcp   LISTEN 0  128   127.0.0.53:53   0.0.0.0:*".to_string(),
            "udp   UNCONN 0  0     127.0.0.1:53    0.0.0.0:*".to_string(),
        ];
        assert!(detect_resolver_conflict(&listeners).is_some());
    }

    #[test]
    fn no_conflict_when_only_stub_listens() {
        let listeners = vec!["tcp   LISTEN 0  128   127.0.0.53:53   0.0.0.0:*".to_string()];
        assert!(detect_resolver_conflict(&listeners).is_none());
    }

    fn observation(data: DnsObservation) -> Observation {
        Observation::new(serde_json::to_value(&data).unwrap())
    }

    fn base_data() -> DnsObservation {
        let config = dnsmasq_config();
        let desired = desired_dnsmasq_conf(&config);
        DnsObservation {
            resolv_conf_current: Some("nameserver 127.0.0.1\n".to_string()),
            resolv_conf_owner: Some("dnsmasq".to_string()),
            search_domains: vec!["dublinux.lan".to_string()],
            port_53_listeners: vec!["udp UNCONN 0 0 127.0.0.1:53 0.0.0.0:*".to_string()],
            resolver_conflict: None,
            dnsmasq_installed: true,
            dnsmasq_active: true,
            dnsmasq_conf_current: desired.clone(),
            dnsmasq_conf_desired: desired,
        }
    }

    fn dnsmasq_config() -> DnsConfig {
        DnsConfig {
            enabled: true,
            provider: "dnsmasq".to_string(),
            local_domains: vec!["dublinux.lan".to_string()],
            listen: vec!["127.0.0.1".to_string()],
            encrypted_upstream_address: String::new(),
        }
    }

    fn config() -> crate::config::DebkitConfig {
        let mut config = crate::config::DebkitConfig::default();
        config.dns = dnsmasq_config();
        config
    }

    #[test]
    fn compliant_when_everything_matches() {
        let config = config();
        let ctx = Context {
            hostname: "iris".to_string(),
            config: &config,
        };
        let diagnosis = NetworkDns.diagnose(&ctx, &observation(base_data()));
        assert!(diagnosis.compliant);
        let plan = NetworkDns
            .plan(&ctx, &observation(base_data()), &diagnosis)
            .unwrap();
        assert!(plan.is_empty());
    }

    #[test]
    fn missing_dnsmasq_conf_produces_write_and_service_changes() {
        let mut data = base_data();
        data.dnsmasq_conf_current = None;
        data.dnsmasq_active = false;
        let config = config();
        let ctx = Context {
            hostname: "iris".to_string(),
            config: &config,
        };
        let diagnosis = NetworkDns.diagnose(&ctx, &observation(data.clone()));
        assert!(!diagnosis.compliant);
        let plan = NetworkDns
            .plan(&ctx, &observation(data), &diagnosis)
            .unwrap();
        assert_eq!(plan.changes.len(), 2);
        assert!(matches!(plan.changes[0].change, Change::WriteFile { .. }));
        match &plan.changes[1].change {
            Change::ServiceAction { action, .. } => {
                assert!(matches!(action, ServiceActionKind::EnableNow));
            }
            other => panic!("expected ServiceAction, got {other:?}"),
        }
    }

    #[test]
    fn active_dnsmasq_with_drifted_conf_restarts_instead_of_enabling() {
        let mut data = base_data();
        data.dnsmasq_conf_current = Some("stale content\n".to_string());
        let config = config();
        let ctx = Context {
            hostname: "iris".to_string(),
            config: &config,
        };
        let diagnosis = NetworkDns.diagnose(&ctx, &observation(data.clone()));
        assert!(!diagnosis.compliant);
        let plan = NetworkDns
            .plan(&ctx, &observation(data), &diagnosis)
            .unwrap();
        assert_eq!(plan.changes.len(), 2);
        match &plan.changes[1].change {
            Change::ServiceAction { action, .. } => {
                assert!(matches!(action, ServiceActionKind::Restart));
            }
            other => panic!("expected ServiceAction, got {other:?}"),
        }
    }

    #[test]
    fn conflict_refuses_to_plan() {
        let mut data = base_data();
        data.resolver_conflict = Some(vec!["systemd-resolved".to_string(), "dnsmasq".to_string()]);
        let config = config();
        let ctx = Context {
            hostname: "iris".to_string(),
            config: &config,
        };
        let diagnosis = NetworkDns.diagnose(&ctx, &observation(data.clone()));
        assert!(diagnosis.conflict.is_some());
        let result = NetworkDns.plan(&ctx, &observation(data), &diagnosis);
        assert!(result.is_err());
    }

    #[test]
    fn resolver_not_pointing_at_dnsmasq_is_flagged_but_not_planned() {
        let mut data = base_data();
        data.resolv_conf_owner = Some("NetworkManager".to_string());
        let config = config();
        let ctx = Context {
            hostname: "iris".to_string(),
            config: &config,
        };
        let diagnosis = NetworkDns.diagnose(&ctx, &observation(data.clone()));
        assert!(!diagnosis.compliant);
        assert!(
            diagnosis
                .findings
                .iter()
                .any(|finding| finding.contains("owned by `NetworkManager`"))
        );
        let plan = NetworkDns
            .plan(&ctx, &observation(data), &diagnosis)
            .unwrap();
        assert!(plan.is_empty(), "resolv.conf ownership is not auto-fixed");
    }

    #[test]
    fn disabled_config_is_always_compliant() {
        let config = crate::config::DebkitConfig::default();
        let ctx = Context {
            hostname: "iris".to_string(),
            config: &config,
        };
        let mut data = base_data();
        data.resolver_conflict = Some(vec!["a".to_string(), "b".to_string()]);
        let diagnosis = NetworkDns.diagnose(&ctx, &observation(data.clone()));
        assert!(diagnosis.compliant);
        let plan = NetworkDns
            .plan(&ctx, &observation(data), &diagnosis)
            .unwrap();
        assert!(plan.is_empty());
    }
}
